ci: add error log collection

diff --git a/.github/workflows/ci-java21.yml b/.github/workflows/ci-java21.yml
--- a/.github/workflows/ci-java21.yml
+++ b/.github/workflows/ci-java21.yml
@@ -150,6 +150,26 @@ jobs:
       - name: Run tests
         run: bats --tap test/bats/0*.bats
 
+      - name: debug logs
+        if: failure()
+        run: |
+            docker logs exist-ci | grep 'ERROR'
+            docker logs nonroot | grep 'ERROR'
+
+      - name: Capture container logs on failure
+        if: failure()
+        run: |
+          echo "Capturing container stdout/stderr..."
+          docker logs exist-ci > exist.log 2>&1 || true
+          docker logs nonroot > exist-nr.log 2>&1 || true
+
+      - name: Upload logs artifact
+        if: failure()
+        uses: actions/upload-artifact@v7
+        with:
+          name: exist-${{ env.CACHE_SCOPE }}-failed-log
+          path: exist*.log
+
       # DP: this dynamically set the version from develop
       # no longer necessary
       # - name: Get SemVer string from test image
